from collections.abc import Iterator, Mapping, MutableMapping as MutableMappingType
from typing import Any, Self, TypeVar

from _typeshed import Incomplete

T = TypeVar('T', bound=Any)

class cidict(MutableMappingType[str, T]):
    def __init__(self, default: Mapping[str, T] | None = ...) -> None: ...
    def __getitem__(self, key: str) -> T: ...
    def __setitem__(self, key: str, value: T) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def clear(self) -> None: ...
    def copy(self) -> Self: ...
    __copy__: Incomplete
    def has_key(self, key: str) -> bool: ...
    @property
    def data(self) -> dict[str, T]: ...

def strlist_minus(a: list[str], b: list[str]) -> list[str]: ...
def strlist_intersection(a: list[str], b: list[str]) -> list[str]: ...
def strlist_union(a: list[str], b: list[str]) -> list[str]: ...
