def escape_dn_chars(s: str) -> str: ...
def str2dn(dn: str, flags: int = ...) -> list[list[tuple[str, str, int]]]: ...
def dn2str(dn: list[list[tuple[str, str, int]]], flags: int = ...) -> str: ...
def explode_dn(dn: str, notypes: bool = ..., flags: int = ...) -> list[str]: ...
def explode_rdn(rdn: str, notypes: bool = ..., flags: int = ...) -> list[str]: ...
def is_dn(s: str, flags: int = ...) -> bool: ...
def normalize(s: str, flags: int = ...) -> str: ...
