from collections.abc import Iterable

from ldap.functions import strf_secs as strf_secs

def escape_filter_chars(assertion_value: str, escape_mode: int = ...) -> str: ...
def filter_format(filter_template: str, assertion_values: Iterable[str]) -> str: ...
def time_span_filter(filterstr: str = ..., from_timestamp: float = ..., until_timestamp: float | None = ..., delta_attr: str = ...) -> str: ...
