from typing import Any, BinaryIO, TextIO

import ldap.functions
import ldap.sasl
from _ldap import NO_SUCH_OBJECT
from _typeshed import Incomplete
from ldap.controls import RequestControl, ResponseControl
from ldap.extop import PasswordModifyResponse
from ldap.types import LDAPAddModList, LDAPEntryDict, LDAPModifyModList, LDAPSearchResult

class LDAPBytesWarning(BytesWarning):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class NO_UNIQUE_ENTRY(NO_SUCH_OBJECT): ...

class SimpleLDAPObject:
    CLASSATTR_OPTION_MAPPING: Incomplete
    timeout: int
    protocol_version: Incomplete
    def __init__(
        self,
        uri: str | None,
        trace_level: int = ...,
        trace_file: TextIO | None = ...,
        trace_stack_limit: int = ...,
        bytes_mode: Any | None = ...,
        bytes_strictness: str | None = ...,
        fileno: int | BinaryIO | None = ...,
    ) -> None: ...
    @property
    def bytes_mode(self) -> bool: ...
    @property
    def bytes_strictness(self) -> str: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def fileno(self) -> int: ...
    def abandon_ext(self, msgid: int, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...) -> None: ...
    def abandon(self, msgid: int) -> None: ...
    def cancel(self, cancelid: int, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...) -> int: ...
    def cancel_s(
        self, cancelid: int, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> int | None: ...
    def add_ext(
        self, dn: str, modlist: LDAPAddModList, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> int: ...
    def add_ext_s(
        self, dn: str, modlist: LDAPAddModList, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> tuple[Any, Any, Any, Any]: ...
    def add(self, dn: str, modlist: LDAPAddModList) -> int: ...
    def add_s(self, dn: str, modlist: LDAPAddModList) -> tuple[Any, Any, Any, Any]: ...
    def simple_bind(
        self,
        who: str | None = ...,
        cred: str | None = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
    ) -> int: ...
    def simple_bind_s(
        self,
        who: str | None = ...,
        cred: str | None = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
    ) -> tuple[Any, Any, Any, Any]: ...
    def bind(self, who: str, cred: str, method: int = ...) -> int: ...
    def bind_s(self, who: str, cred: str, method: int = ...) -> None: ...
    def sasl_interactive_bind_s(
        self,
        who: str,
        auth: ldap.sasl.sasl,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        sasl_flags: int = ...,
    ) -> None: ...
    def sasl_non_interactive_bind_s(
        self,
        sasl_mech: str,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        sasl_flags: int = ...,
        authz_id: str = ...,
    ) -> None: ...
    def sasl_external_bind_s(
        self,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        sasl_flags: int = ...,
        authz_id: str = ...,
    ) -> None: ...
    def sasl_gssapi_bind_s(
        self,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        sasl_flags: int = ...,
        authz_id: str = ...,
    ) -> None: ...
    def sasl_bind_s(
        self, dn: str, mechanism: str, cred: str, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> int | str: ...
    def compare_ext(
        self, dn: str, attr: str, value: bytes, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> int: ...
    def compare_ext_s(
        self, dn: str, attr: str, value: bytes, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> bool: ...
    def compare(self, dn: str, attr: str, value: bytes) -> int: ...
    def compare_s(self, dn: str, attr: str, value: bytes) -> bool: ...
    def delete_ext(self, dn: str, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...) -> int: ...
    def delete_ext_s(
        self, dn: str, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> tuple[Any, Any, Any, Any]: ...
    def delete(self, dn: str) -> int: ...
    def delete_s(self, dn: str) -> None: ...
    def extop(
        self, extreq: ldap.extop.ExtendedRequest, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> int: ...
    def extop_result(self, msgid: int = ..., all: int = ..., timeout: float | None = ...) -> tuple[str, bytes]: ...
    def extop_s(
        self,
        extreq: ldap.extop.ExtendedRequest,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        extop_resp_class: type[ldap.extop.ExtendedResponse] | None = ...,
    ) -> tuple[str, bytes] | ldap.extop.ExtendedResponse: ...
    def modify_ext(
        self, dn: str, modlist: LDAPModifyModList, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> int: ...
    def modify_ext_s(
        self, dn: str, modlist: LDAPModifyModList, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> tuple[Any, Any, Any, Any]: ...
    def modify(self, dn: str, modlist: LDAPModifyModList) -> int: ...
    def modify_s(self, dn: str, modlist: LDAPModifyModList) -> None: ...
    def modrdn(self, dn: str, newrdn: str, delold: int = ...) -> int: ...
    def modrdn_s(self, dn: str, newrdn: str, delold: int = ...) -> None: ...
    def passwd(
        self, user: str, oldpw: str, newpw: str, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...
    ) -> int: ...
    def passwd_s(
        self,
        user: str,
        oldpw: str,
        newpw: str,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        extract_newpw: bool = ...,
    ) -> tuple[str, bytes | PasswordModifyResponse]: ...
    def rename(
        self,
        dn: str,
        newrdn: str,
        newsuperior: str | None = ...,
        delold: int = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
    ) -> int: ...
    def rename_s(
        self,
        dn: str,
        newrdn: str,
        newsuperior: str | None = ...,
        delold: int = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
    ) -> None: ...
    def result(self, msgid: int = ..., all: int = ..., timeout: float | None = ...) -> tuple[int | None, Any | None]: ...
    def result2(self, msgid: int = ..., all: int = ..., timeout: float | None = ...) -> tuple[int | None, Any | None, int | None]: ...
    def result3(
        self, msgid: int = ..., all: int = ..., timeout: float | None = ..., resp_ctrl_classes: dict[str, type[ResponseControl]] | None = ...
    ) -> tuple[int | None, list[LDAPSearchResult] | None, int | None, list[ResponseControl] | None]: ...
    def result4(
        self,
        msgid: int = ...,
        all: int = ...,
        timeout: float | None = ...,
        add_ctrls: int = ...,
        add_intermediates: int = ...,
        add_extop: int = ...,
        resp_ctrl_classes: dict[str, type[ResponseControl]] | None = ...,
    ) -> tuple[int | None, list[LDAPSearchResult] | None, int | None, list[ResponseControl] | None, str | None, bytes | None]: ...
    def search_ext(
        self,
        base: str,
        scope: int,
        filterstr: str | None = ...,
        attrlist: list[str] | None = ...,
        attrsonly: int = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        timeout: float = ...,
        sizelimit: int = ...,
    ) -> int: ...
    def search_ext_s(
        self,
        base: str,
        scope: int,
        filterstr: str | None = ...,
        attrlist: list[str] | None = ...,
        attrsonly: int = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        timeout: float = ...,
        sizelimit: int = ...,
    ) -> list[tuple[str, LDAPEntryDict]]: ...
    def search(self, base: str, scope: int, filterstr: str | None = ..., attrlist: list[str] | None = ..., attrsonly: int = ...) -> int: ...
    def search_s(
        self, base: str, scope: int, filterstr: str | None = ..., attrlist: list[str] | None = ..., attrsonly: int = ...
    ) -> list[tuple[str, LDAPEntryDict]]: ...
    def search_st(
        self, base: str, scope: int, filterstr: str | None = ..., attrlist: list[str] | None = ..., attrsonly: int = ..., timeout: float = ...
    ) -> list[tuple[str, LDAPEntryDict]]: ...
    def start_tls_s(self) -> None: ...
    def unbind_ext(self, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...) -> int: ...
    def unbind_ext_s(self, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...) -> None: ...
    def unbind(self) -> int: ...
    def unbind_s(self) -> None: ...
    def whoami_s(self, serverctrls: list[RequestControl] | None = ..., clientctrls: list[RequestControl] | None = ...) -> str: ...
    def get_option(self, option: int) -> int | str | list[RequestControl]: ...
    def set_option(self, option: int, invalue: Any) -> Any: ...
    def search_subschemasubentry_s(self, dn: str | None = ...) -> str | None: ...
    def read_s(
        self,
        dn: str,
        filterstr: str | None = ...,
        attrlist: list[str] | None = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        timeout: float = ...,
    ) -> LDAPEntryDict | None: ...
    def read_subschemasubentry_s(self, subschemasubentry_dn: str, attrs: list[str] | None = ...) -> LDAPEntryDict | None: ...
    def find_unique_entry(
        self,
        base: str,
        scope: int,
        filterstr: str | None = ...,
        attrlist: list[str] | None = ...,
        attrsonly: int = ...,
        serverctrls: list[RequestControl] | None = ...,
        clientctrls: list[RequestControl] | None = ...,
        timeout: float = ...,
    ) -> tuple[str, LDAPEntryDict]: ...
    def read_rootdse_s(self, filterstr: str | None = ..., attrlist: list[str] | None = ...) -> LDAPEntryDict | None: ...
    def get_naming_contexts(self) -> list[bytes]: ...

class ReconnectLDAPObject(SimpleLDAPObject):
    __transient_attrs__: Incomplete
    def __init__(
        self,
        uri: str | None,
        trace_level: int = ...,
        trace_file: TextIO | None = ...,
        trace_stack_limit: int = ...,
        bytes_mode: Any | None = ...,
        bytes_strictness: str | None = ...,
        retry_max: int = ...,
        retry_delay: float = ...,
        fileno: int | BinaryIO | None = ...,
    ) -> None: ...
    def passwd_s(self, *args: Any, **kwargs: Any) -> tuple[str, bytes | PasswordModifyResponse]: ...
    def reconnect(self, uri: str, retry_max: int = ..., retry_delay: float = ..., force: bool = ...) -> None: ...
    def set_option(self, option: int, invalue: Any) -> Any: ...
    def bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def simple_bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def start_tls_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def sasl_interactive_bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def sasl_bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancel_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def compare_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def extop_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def modify_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def rename_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def search_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def whoami_s(self, *args: Any, **kwargs: Any) -> Any: ...

LDAPObject = SimpleLDAPObject
