from collections.abc import Iterator, MutableMapping
from typing import TypeAlias

from _typeshed import Incomplete

LDAP_SCOPE_BASE: int
LDAP_SCOPE_ONELEVEL: int
LDAP_SCOPE_SUBTREE: int
SEARCH_SCOPE_STR: Incomplete
SEARCH_SCOPE: Incomplete

def isLDAPUrl(s: str) -> bool: ...

class LDAPUrlExtension:
    critical: Incomplete
    extype: Incomplete
    exvalue: Incomplete
    def __init__(self, extensionStr: str | None = ..., critical: int = ..., extype: str | None = ..., exvalue: str | None = ...) -> None: ...
    def unparse(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

LDAPUrlExtensionsBase: TypeAlias = MutableMapping[(str, LDAPUrlExtension)]

class LDAPUrlExtensions(LDAPUrlExtensionsBase):
    def __init__(self, default: dict[str, LDAPUrlExtension] | None = ...) -> None: ...
    def __setitem__(self, name: str, value: LDAPUrlExtension) -> None: ...
    def __getitem__(self, name: str) -> LDAPUrlExtension: ...
    def __delitem__(self, name: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def parse(self, extListStr: str) -> None: ...
    def unparse(self) -> str: ...

class LDAPUrl:
    attr2extype: Incomplete
    urlscheme: Incomplete
    hostport: Incomplete
    dn: Incomplete
    attrs: Incomplete
    scope: Incomplete
    filterstr: Incomplete
    extensions: Incomplete
    who: Incomplete
    cred: Incomplete
    def __init__(
        self,
        ldapUrl: str | None = ...,
        urlscheme: str = ...,
        hostport: str = ...,
        dn: str = ...,
        attrs: list[str] | None = ...,
        scope: int | None = ...,
        filterstr: str | None = ...,
        extensions: LDAPUrlExtensions | None = ...,
        who: str | None = ...,
        cred: str | None = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def applyDefaults(self, defaults: dict[str, str]) -> None: ...
    def initializeUrl(self) -> str: ...
    def unparse(self) -> str: ...
    def htmlHREF(self, urlPrefix: str = ..., hrefText: str | None = ..., hrefTarget: str | None = ...) -> str: ...
    def __getattr__(self, name: str) -> str | None: ...
    def __setattr__(self, name: str, value: str) -> None: ...
    def __delattr__(self, name: str) -> None: ...
