import logging
import unittest
from collections.abc import Callable
from types import TracebackType
from typing import Any, Self, TypeVar

from _typeshed import Incomplete

HERE: Incomplete
SLAPD_CONF_TEMPLATE: str
LOCALHOST: str
CI_DISABLED: Incomplete
HAVE_LDAPI: bool
T = TypeVar('T', bound=Any)

def identity(test_item: T) -> T: ...
def skip_unless_ci(reason: str, feature: str | None = None) -> Callable[..., Any]: ...
def requires_tls() -> Callable[..., Any]: ...
def requires_sasl() -> Callable[..., Any]: ...
def requires_ldapi() -> Callable[..., Any]: ...
def requires_init_fd() -> Callable[..., Any]: ...
def combined_logger(
    log_name: str,
    log_level: int = ...,
    sys_log_format: str = '%(levelname)s %(message)s',
    console_log_format: str = '%(asctime)s %(levelname)s %(message)s',
) -> logging.Logger: ...

class SlapdObject:
    slapd_conf_template = SLAPD_CONF_TEMPLATE
    database: str
    suffix: str
    root_cn: str
    root_pw: str
    slapd_loglevel: str
    local_host = LOCALHOST
    testrunsubdirs: Incomplete
    openldap_schema_files: Incomplete
    TMPDIR: Incomplete
    SCHEMADIR: str | None
    BIN_PATH: Incomplete
    SBIN_PATH: Incomplete
    server_id: Incomplete
    testrundir: Incomplete
    ldap_uri: Incomplete
    ldapi_uri: str | None
    default_ldap_uri: Incomplete
    cli_sasl_external: Incomplete
    cafile: Incomplete
    servercert: Incomplete
    serverkey: Incomplete
    clientcert: Incomplete
    clientkey: Incomplete
    def __init__(self) -> None: ...
    @property
    def root_dn(self) -> str: ...
    @property
    def hostname(self) -> str: ...
    @property
    def port(self) -> int: ...
    def setup_rundir(self) -> None: ...
    def gen_config(self) -> str: ...
    def start(self) -> None: ...
    def stop(self, cleanup: bool = True) -> None: ...
    def restart(self) -> None: ...
    def terminate(self) -> None: ...
    def resume(self) -> None: ...
    def wait(self) -> None: ...
    def ldapwhoami(self, extra_args: list[str] | None = None) -> None: ...
    def ldapadd(self, ldif: str, extra_args: list[str] | None = None) -> None: ...
    def ldapmodify(self, ldif: str, extra_args: list[str] | None = None) -> None: ...
    def ldapdelete(self, dn: str, recursive: bool = False, extra_args: list[str] | None = None) -> None: ...
    def slapadd(self, ldif: str | None, extra_args: list[str] | None = None) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class SlapdTestCase(unittest.TestCase):
    server_class = SlapdObject
    server: Incomplete
    ldap_object_class: Incomplete
    @classmethod
    def setUpClass(cls) -> None: ...
    @classmethod
    def tearDownClass(cls) -> None: ...
